services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped  # <--- NÊN BẬT (Tự chạy lại trừ khi bạn tắt thủ công)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "404"
      POSTGRES_DB: qlth
    ports:
      - "5432:5432"
    
    # --- THÊM PHẦN NÀY ---
    volumes:
      # 1. Tự động chạy init.sql khi khởi tạo
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
      # 2. (Tùy chọn) Giữ dữ liệu bền vững để không mất khi tắt máy
      # - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: unless-stopped # <--- NÊN BẬT
    ports:
      - "8080:8080"
    depends_on:
      - db

  app:
    build: .
    container_name: ptud_app
    # restart: on-failure  <--- MỞ CÁI NÀY KHI CODE ĐÃ ỔN ĐỊNH
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: qlth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "404"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy